title: Your awesome title
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
defaults:
  -
    scope:
      path: "" 
    values:
      layout: "default"
collections:
  architecture:
    output: true
    title: Architecture
    icon: cubes
  documentation:
    output: true
    title: Documentation
    icon: book
  concepts:
    output: true
    title: Concepts
    icon: university